language: node_js
node_js:
  - "node"

cache: yarn

script: yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: "a96901666ba78365b1f743969f212f068315da9c"
  local_dir: dist
  on:
    branch: master